version: "3.9"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    links:
      - zookeeper
#  db:
#    image: "neo4j:latest"
#    restart: always
#    ports:
#      - "7474:7474" 
#      - "7687:7687"
#    hostname: develboarddatabase
#    container_name: develboarddatabase
#    environment:
#      - NEO4J_AUTH=neo4j/s3cr3t
#  backend:
#    build:
#      context: ./backend/
#      dockerfile: Dockerfile
#    restart: always
#    ports:
#      - "3000:3000"
#    hostname: develboardbackend
#    container_name: develboardbackend
#    depends_on:
#      - db
#  frontend:
#    restart: always
#    build:
#      context: ./frontend/
#      dockerfile: Dockerfile
#    ports:
#      - "4200:4200"
#    hostname: develboardfrontend
#    container_name: develboardfrontend
#    depends_on:
#      - backend
