version: "3.9"

services:

  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: unless-stopped
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    restart: unless-stopped
    container_name: develboardkafka
    hostname: develboardkafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: develboardkafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    links:
      - zookeeper

  db:
    image: "neo4j:latest"
    restart: unless-stopped
    ports:
      - "7474:7474" 
      - "7687:7687"
    hostname: develboarddatabase
    container_name: develboarddatabase
    environment:
      - NEO4J_AUTH=neo4j/s3cr3ttt

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    hostname: develboardbackend
    container_name: develboardbackend
    depends_on:
      - kafka

  users-consumer:
    build:
      context: ./backend/services/users/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: develboardusersconsumer
    depends_on:
      - db
      - kafka
      - backend

  leaderboards-consumer:
    build:
      context: ./backend/services/leaderboards/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: develboardleaderboardsconsumer
    depends_on:
      - db
      - kafka
      - backend

  code-evaluation-consumer:
    build:
      context: ./backend/services/evaluateCode/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: develboardcodeevaluationconsumer
    depends_on:
      - db
      - kafka
      - backend

  challenges-consumer:
    build:
      context: ./backend/services/challenges/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: develboardchallengesconsumer
    depends_on:
      - db
      - kafka
      - backend

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    hostname: develboardfrontend
    container_name: develboardfrontend
    depends_on:
      - backend
